#!/bin/sh

export AMBERHOME="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

"$AMBERHOME/bin_linux/teLeap_mod_static_x86_64" \
           -I"$AMBERHOME/dat/leap/prep" \
           -I"$AMBERHOME/dat/leap/lib" \
           -I"$AMBERHOME/dat/leap/parm" \
           -I"$AMBERHOME/dat/leap/cmd" \
            $*
